language: ruby

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head

gemfile:
  - Gemfile

branches:
  only:
    - master

before_install: gem update bundler
script:
  - bundle exec rake test
  - bundle exec rubocop

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
